HPC_center/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #url for APP document
    path('document/', include('document.urls', namespace='document')),
    
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),

    path('tutorial/', include('tutorial.urls', namespace='tutorial')),

    path('', include('mainpage.urls')),

    path('ticket/', include('ticket.urls', namespace='ticket')),

    path('comment/', include('comment.urls', namespace='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/urls.py
# 引入path
from django.urls import path
from ticket import views

# 正在部署的应用的名称
app_name = 'ticket'

urlpatterns = [
    path('ticket_list/', views.ticket_list, name='ticket_list'),
    path('ticket_userList/<int:id>', views.ticket_userList,name='ticket_userList'),
    path('ticket_detail/<int:id>/', views.ticket_detail, name='ticket_detail'),
    path('ticket_create/' , views.ticket_create, name='ticket_create'),
    path('ticket_delete/<int:id>/', views.ticket_delete, name='ticket_delete'),
    path('ticket_update/<int:id>/', views.ticket_update, name='ticket_update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
    path('display/<int:id>/', views.profile_display, name='display'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
# 引入内置信号
from django.db.models.signals import post_save
# 引入信号接收器的装饰器
from django.dispatch import receiver
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    #姓名
    real_name = models.CharField(max_length=40,blank=True)
    #部门
    department = models.CharField(max_length=40,blank=True)
    #职位
    position = models.CharField(max_length=40,blank=True)
    #学校
    college = models.CharField(max_length=40,blank=True)
    #头像
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
     # 个人简介
    bio = models.TextField(max_length=500, blank=True)
    
    is_engineer = models.BooleanField(default=False)


    def __str__(self):
        return 'user {}'.format(self.user.username)

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

class UserRegisterForm(forms.ModelForm):
    # 复写 User 的密码
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email')

    # 对两次输入的密码是否一致进行检查
    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            print(data.get('password'))
            return data.get('password')
        else:
            raise forms.ValidationError("密码输入不一致,请重试。")
    
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('real_name', 'department', 'position', 'college', 'avatar', 'bio')

userprofile/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .forms import UserLoginForm, UserRegisterForm, ProfileForm
from django.contrib.auth.models import User
from .models import Profile
from document.models import DocumentPost
from ticket.models import TicketPost
from comment.models import Comment
import markdown

# Create your views here.
def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(request.POST)
        if user_login_form.is_valid():
            data = user_login_form.cleaned_data
            user = authenticate(username=data['username'],password=data['password'])
            if user:
                login(request, user)
                return redirect("mainpage:index")
            else:
                return HttpResponse("账号密码有误")
        else:
            return HttpResponse("账号密码不合法")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = {'form':user_login_form}
        return render(request,'userprofile/login.html',context)
    else:
        return HttpResponse("请求非法")

def user_logout(request):
    logout(request)
    return redirect("mainpage:index")

def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        print(user_register_form.is_valid())
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            # 保存好数据后立即登录并返回博客列表页面
            login(request, new_user)
            return redirect("mainpage:index")
        else:
            return HttpResponse(user_register_form.errors)
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = { 'form': user_register_form }
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("请求非法")

@login_required(login_url='/userprofile/login/')
def profile_edit(request, id):
    user = User.objects.get(id=id)
    if Profile.objects.filter(user_id=id).exists():
        profile = Profile.objects.get(user_id=id)
    else:
        profile = Profile.objects.create(user=user)

    # user_id 是 OneToOneField 自动生成的字段
    #profile = Profile.objects.get(user_id = id)

    if request.method == 'POST':
        if request.user != user:
            return HttpResponse("没有权限修改此用户信息")
        profile_form = ProfileForm(request.POST,request.FILES)
        if profile_form.is_valid():
            profile_cleaned_data = profile_form.cleaned_data
            profile.real_name = profile_cleaned_data['real_name']
            profile.department = profile_cleaned_data['department']
            profile.position = profile_cleaned_data['position']
            profile.college = profile_cleaned_data['college']
            #profile.avatar = profile_cleaned_data['avatar']
            profile.bio = profile_cleaned_data['bio']
            if 'avatar' in request.FILES:
                profile.avatar = profile_cleaned_data["avatar"]
                print(profile.avatar)
            profile.save()
            return redirect('mainpage:index')
        else:
            return HttpResponse(profile_form.errors)
    elif request.method == 'GET':
        context = { 'profile': profile, 'user': user }
        return render(request, 'userprofile/edit.html', context)
    else:
        return HttpResponse("请求非法")    
    
@login_required(login_url='/userprofile/login/')
def profile_display(request, id):
    user = User.objects.get(id=id)
    if Profile.objects.filter(user_id=id).exists():
        profile = Profile.objects.get(user_id=id)
    else:
        profile = Profile.objects.create(user=user)
    md = markdown.Markdown(
        extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
        'markdown.extensions.fenced_code',
        'markdown.extensions.tables',
        ]
    )
    profile.bio = md.convert(profile.bio)
    context = { 'profile': profile, 'user': user }
    context['num_of_documents'] = DocumentPost.objects.filter(author=user).count()
    context['num_of_tickets'] = TicketPost.objects.filter(author=user).count()
    context['num_of_comments'] = Comment.objects.filter(user=user).count()
    return render(request, 'userprofile/display.html', context)

templates/userprofile/display.html
{% extends "base.html" %} {% load static %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
<div class="container">
    <div class="panel panel-default" id="body-content">
        <div class="panel-body">
            <div style="background-color: #1c2b36;height: 29vh">
                <div class="wrapper-lg">
                    <div style="text-align: center;">
                        <a>
                            {% if profile.avatar %}
                                <img src="{{ user.profile.avatar.url }}" class="img-circle" style="border-radius: 50%; width: 256px; height: 256px;">
                            {% else %}
                                <img src="{%static 'png/logo.png' %}" class="img-circle" style="border-radius: 50%; width: 216px; height: 216px;">
                            {% endif %}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="height: 56vh">
        <div class="wrapper-lg" style="padding-left: 0; padding-right: 0;padding-top: 0;">
            <div class="row" style="text-align: center;">
                <div class="col-sm-8" style="padding-top: 15px;">

                    <table class="table table-bordered" style="font-size: 14px;color: #000">
                        <tbody>
                        <tr style="background-color: #1c2b36;font-size: 16px; font-weight: bolder;color: white;">
                            <td colspan="4">基本信息</td>
                        </tr>
                        <tr class="gradeX odd" role="row">
                            <td class="text-right" style="width: 20%; font-weight: bolder;">姓名</td>
                            <td style="width: 30%">
                                {{ user.profile.real_name }}</td>
                            <td class="text-right" style="width: 20%; font-weight: bolder;">用户名</td>
                            <td style="width: 30%">{{ user.username }}
                            </td>
                        </tr>
                        <tr class="gradeX odd" role="row">
                            <td class="text-right" style="width: 20%; font-weight: bolder;">部门</td>
                            <td style="width: 30%">{{ user.profile.department }}</td>
                            <td class="text-right" style="width: 20%; font-weight: bolder;">职位</td>
                            <td style="width: 30%">{{ user.profile.position }}</td>
                        </tr>
                        <tr class="gradeX odd" role="row">
                            <td class="text-right" style="width: 20%; font-weight: bolder;">学校</td>
                            <td style="width: 30%">{{ user.profile.college }}</td>
                            <td class="text-right" style="width: 20%; font-weight: bolder;"></td>
                            <td style="width: 30%"></td>
                        </tr>
                        </tbody>
                    </table>


                    <table class="table table-bordered" style="font-size: 14px;color: #000">
                        <tbody>
                        <tr style="background-color: #1c2b36;font-size: 16px; font-weight: bolder;color: white;">
                            <td colspan="4">统计</td>
                        </tr>
                        <tr class="gradeX odd" role="row">
                            <td class="text-right" style="width: 20%; font-weight: bolder;">发贴数</td>
                            <td style="width: 30%">
                                {{ num_of_tickets }}</td>
                            <td class="text-right" style="width: 20%; font-weight: bolder;">评论数</td>
                            <td style="width: 30%">
                                {{ num_of_comments }}</td>
                        </tr>
                       
                        </tbody>
                    </table>
                </div>
                <div class="col-sm-4" style="padding-top: 15px;padding-left: 0;">

                    <table class="table table-bordered" style="font-size: 14px;color: #000">
                        <tbody>
                        <tr style="background-color: #1c2b36;font-size: 16px; font-weight: bolder;color: white;">
                            <td>其他说明</td>
                        </tr>
                        <tr class="gradeX odd" style="height: 40vh;" role="row">
                            <td class="text-left">
                                <p>{{ profile.bio | safe}}</p></td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="row">
                <a class="col-3 btn btn-primary bg-dark" style="color: white;margin-right: 100px;" href='{% url "userprofile:edit" user.id %}'>编辑资料</a>
                <a class="col-3 btn btn-primary bg-dark" style="color: white;margin-left: 100px;" href='{% url "userprofile:logout"%}'>登出账号</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/userprofile/edit.html
{% extends "base.html" %} {% load static %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">用户名: {{ user.username }}</div>
            <a class="btn btn-primary " href="{% url 'userprofile:logout' %}">登出</a>
            <br>
            {% if profile.avatar %}
                <div class="col-md-4">头像</div>
                <img src="{{ profile.avatar.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4">
            {% else %}
                <h5 class="col-md-4">暂无头像</h3>
            {% endif %}
            <br>
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <!-- avatar -->
                <div class="form-group">
                    <label for="avatar">上传头像</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
            
            <!-- <form method="post" action=".">
                {% csrf_token %} -->
                
                <div class="form-group col-md-4">
                    <label for="real_name">姓名</label>
                    <input type="text" class="form-control" id="real_name" name="real_name" value="{{ profile.real_name }}">
                </div>
                <div class="form-group col-md-4">
                    <label for="department">部门</label>
                    <input type="text" class="form-control" id="department" name="department" value="{{ profile.department }}">
                </div>
                <div class="form-group col-md-4">
                    <label for="position">职位</label>
                    <input type="text" class="form-control" id="position" name="position" value="{{ profile.position }}">
                </div>
                <div class="form-group col-md-4">
                    <label for="college">学校</label>
                    <input type="text" class="form-control" id="college" name="college" value="{{ profile.college }}">
                </div>
                <!-- bio -->
                <div class="form-group col-md-4">
                    <label for="bio">简介</label>
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/login.html
{% extends "base.html" %} {% load static %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <!-- 密码 -->
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <br>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">登录</button>

                <h5>还没有账号？</h5>
                <h5>点击<a href='{% url "userprofile:register" %}'>注册账号</a>加入我们吧！</h5>
                <br>
                <form method="post" action=".">
                    ...
                </form>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/register.html
{% extends "base.html" %} {% load static %}
{% block title %} 登录 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group col-md-4">
                    <label for="username">昵称</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <!-- 邮箱 -->
                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email">
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-4">
                    <label for="password">设置密码</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <!-- 确认密码 -->
                <div class="form-group col-md-4">
                    <label for="password2">确认密码</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}