HPC_center/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #url for APP document
    path('document/', include('document.urls', namespace='document')),
    
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),

    path('tutorial/', include('tutorial.urls', namespace='tutorial')),

    path('', include('mainpage.urls')),

    path('ticket/', include('ticket.urls', namespace='ticket')),

    path('comment/', include('comment.urls', namespace='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.main_page, name='index'),
]

ticket/urls.py
# 引入path
from django.urls import path
from ticket import views

# 正在部署的应用的名称
app_name = 'ticket'

urlpatterns = [
    path('ticket_list/', views.ticket_list, name='ticket_list'),
    path('ticket_userList/<int:id>', views.ticket_userList,name='ticket_userList'),
    path('ticket_detail/<int:id>/', views.ticket_detail, name='ticket_detail'),
    path('ticket_create/' , views.ticket_create, name='ticket_create'),
    path('ticket_delete/<int:id>/', views.ticket_delete, name='ticket_delete'),
    path('ticket_update/<int:id>/', views.ticket_update, name='ticket_update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
    path('display/<int:id>/', views.profile_display, name='display'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'css/main3.css' %}"> -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
</head>

<body>
<!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
<!-- bootstrap.js 依赖popper.js，因此在这里引入 -->
<!--
    popper.js 采用 cdn 远程引入，意思是你不需要把它下载到本地。
    在实际的开发中推荐静态文件尽量都使用 cdn 的形式。
    教程采用本地引入是为了让读者了解静态文件本地部署的流程。
-->
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/mhDoLbDldZc3qpsJHpLogda//BVZbgYuw6kof4u2FrCedxOtgRZDTHgHUhOCVim" crossorigin="anonymous"></script>
</body>

</html>

templates/footer.html
{% load static %}
<!-- Footer-->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 国家超级计算深圳中心</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏 -->
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      
      <!-- 导航栏商标 -->
        <a class="navbar-brand" href="{% url 'mainpage:index' %}">
            <img src="{%static 'png/logo.png' %}" alt="logo" class="d-inline-block align-text-center  me-2" width="50" height="50">
            国家超级计算深圳中心——HPC小站</a>
        <div>
            <ul class="navbar-nav">
              <!-- 条目 -->
                {% if user.is_authenticated %} 
                
                <!-- <li class="nav-item">
                    <a class="nav-link " href="{% url 'userprofile:logout' %}">登出</a>
                </li> -->
                    {% if user.profile.avatar %}
                        <li class="nav-item ml-md-auto">
                            <a class="nav-link d-block" href="{% url 'userprofile:display' user.id %}" style="width: 80px;height: 80px;"><img src="{{ user.profile.avatar.url }}" alt="暂无头像" style="max-width: 100%; border-radius: 50%;" class="d-inline-block align-text-center"></a>
                        </li>
                    {% else %}
                        <li class="nav-item ml-md-auto">
                            <a class="nav-link d-block" href="{% url 'userprofile:display' user.id %}" style="width: 80px;height: 80px;">{{ user.username }}</a>
                        </li>
                    {% endif %}

                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                </li>  
                {% endif %}
            </ul>     
    </div>
</nav> 