HPC_center/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #url for APP document
    path('document/', include('document.urls', namespace='document')),
    
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),

    path('tutorial/', include('tutorial.urls', namespace='tutorial')),

    path('', include('mainpage.urls')),

    path('ticket/', include('ticket.urls', namespace='ticket')),

    path('comment/', include('comment.urls', namespace='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

document/urls.py
from django.urls import path
from . import views

app_name = 'document'

urlpatterns = [
    # 
    path('document-list', views.document_list, name='document_list'),

    path('document-detail/<int:id>/', views.document_detail, name='document_detail'),

    path('document-create/', views.document_create, name='document_create'),

    path('document-delete/<int:id>/', views.document_delete, name='document_delete'),

    path('document-update/<int:id>/', views.document_update, name='document_update'),

    path('document-search/', views.document_search, name='document_search'),
]

ticket/urls.py
# 引入path
from django.urls import path
from ticket import views

# 正在部署的应用的名称
app_name = 'ticket'

urlpatterns = [
    path('ticket_list/', views.ticket_list, name='ticket_list'),
    path('ticket_userList/<int:id>', views.ticket_userList,name='ticket_userList'),
    path('ticket_detail/<int:id>/', views.ticket_detail, name='ticket_detail'),
    path('ticket_create/' , views.ticket_create, name='ticket_create'),
    path('ticket_delete/<int:id>/', views.ticket_delete, name='ticket_delete'),
    path('ticket_update/<int:id>/', views.ticket_update, name='ticket_update'),
]

document/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.


class DocumentPost(models.Model):
    
    author = models.ForeignKey(User, on_delete=models.CASCADE )

    title = models.CharField(max_length=100 )

    body = models.TextField()

    created_at = models.DateTimeField(default=timezone.now)

    doc_type = models.CharField(max_length=100)

    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.title
        

document/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import DocumentPost
from .form import DocumentPostForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
import markdown
# Create your views here.
def document_list(request):
    document_list = DocumentPost.objects.all()
    # paginator = Paginator(document_list,1)
    # # 获取 url 中的页码
    # page = request.GET.get('page')
    # # 将导航对象相应的页码内容返回给 articles
    # documents = paginator.get_page(page)
    context = {'documents': document_list}
    print(document_list[0].doc_type)
    return render(request, 'document/document_list.html',context)

def document_detail(request, id):
    document = DocumentPost.objects.get(id=id)
    md = markdown.Markdown(
        extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
        'markdown.extensions.fenced_code',
        'markdown.extensions.tables',
        ]
    )
    document.body = md.convert(document.body)
    print(document.body)
    context = {'document': document, 'toc': md.toc }
    print(document)
    
    return render(request, 'document/document_detail.html',context)
@login_required(login_url='/userprofile/login/')
def document_create(request):
    if request.method == 'POST':
        document_post_form = DocumentPostForm(request.POST)
        if document_post_form.is_valid():
            new_document = document_post_form.save(commit=False)
            new_document.author = User.objects.get(id=request.user.id)
            new_document.save()
            print(document_post_form)
            return redirect("document:document_list")
        else :
            return HttpResponse(document_post_form.errors)
    else:
        document_post_form = DocumentPostForm(request.POST)
        context = {'document_post_form': document_post_form}
        return render(request, 'document/document_create.html',context)

@login_required(login_url='/userprofile/login/')
def document_delete(request, id):
    document = DocumentPost.objects.get(id=id)
    if request.user != document.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    document.delete()
    
    return redirect('document:document_list')

@login_required(login_url='/userprofile/login/')
def document_update(request, id):
    document = DocumentPost.objects.get(id=id)
    if request.user != document.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    if request.method == 'POST':
        document_post_form = DocumentPostForm(request.POST)
        document_post_form.doc_type = document.doc_type
        if document_post_form.is_valid():
            document.title = request.POST['title']
            document.body = request.POST['body']
            
            document.save()
            print(document_post_form)
            return redirect("document:document_detail", id=id)
        else :
            return HttpResponse("表单信息有误")
    else:
        document_post_form = DocumentPostForm(request.POST)
        context = {'document':document, 'document_post_form': document_post_form}
        return render(request, 'document/document_update.html',context)



@csrf_exempt
def document_search(request):
    query = request.GET.get('q')
    if query:
        documents = DocumentPost.objects.filter(title__icontains=query) | DocumentPost.objects.filter(body__icontains=query)
    else:
        documents = DocumentPost.objects.all()
    return render(request, 'document/document_list.html', {'documents': documents, 'query': query})
    

templates/document/document_create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文档标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="doc_type">文档类型</label>
                    <!-- 文本框 -->
                    <select type="text" class="form-control" id="doc_type" name="doc_type">
                        <option value="软件编译">软件编译</option>
                        <option value="编译故障">编译故障</option>
                        <option value="使用故障">使用故障</option>
                        <option value="软件测试">软件测试</option>
                        <option value="软件使用">软件使用</option>
                    </select>
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文档正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">添加</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/document/document_detail.html
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文档详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <div class="col-3 mt-4">
            <h4><strong>目录</strong></h4>
            <hr>
            <div>
                {{ toc|safe }}
            </div>
        </div>
        <div class="col-9">
            <!-- 标题及作者 -->
            <h1 class="col-12 mt-4 mb-4">{{ document.title }}</h1>
            <div class="col-12 alert alert-success">作者：{{ document.author }} 文档类型：{{document.doc_type}}</div>

            <!-- 文章正文 -->
            <div class="col-12">
                <p>{{ document.body | safe }}</p>
            </div>
            {% if user == document.author %}
                <a class="col-4 btn btn-primary" href="#" onclick="confirm_delete()">删除文档</a>
                <a class="col-4 btn btn-primary" href='{% url "document:document_update" document.id %}'>编辑文档</a>
            {% endif %}
        </div>
        
    </div>
</div>
<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "document:document_delete" document.id %}'
            },
        })
    }
</script>
{% endblock content %}

templates/document/document_list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文档列表
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}


<!-- <form action="{% url 'document:document_search' %}" method="get">
	
    <div class="form-group, container my-4">
        <label for="search-input">搜索文档：</label>
        <input type="text" class="form-control" id="search-input" name="q" value="{{ query }}">
    </div>
    <button type="submit" class="btn btn-primary">搜索</button>
	
</form> -->

<br>
<div class="container">
    <div class="row ">
		<div class="col-sm-2">
			{% if user.is_authenticated %} 
				<a href="{% url 'document:document_create' %}" class="btn btn-primary">新增文档</a>
			{% endif %}
		</div>
		<div class="col-sm-8 row">
			<form action="{% url 'document:document_search' %}" method="get" class="col-sm-8 row">
				<label for="search-input" class="col-sm-4">搜索文档：</label>
				<div class="col-sm-6	">
					<input type="text" class="form-control" id="search-input" name="q" value="{{ query }}">
				</div>
				<div class="form-group, col-sm-2"> 
					<button type="submit" class="btn btn-primary">搜索</button>
				</div>
			</form>
		</div>
	</div>
</div>
<br>
<br>
<div class="container">
	{% if documents %}
		<ul>
			{% for document in documents %}
			<div class="row">
				<button type="button" class="btn btn-sm md btn-success" style="width: 100px;">{{ document.doc_type }}</button>
				<!-- 标题 -->
				<h4>
					<b>
						<a href="{% url 'document:document_detail' document.id %}"
						style="color: black;" 
						>
							{{ document.title }}
						</a>
					</b>
				</h4>
				<!-- 摘要 -->
				<div>
					<p style="color: gray;">
						{{ document.body|slice:'100' }}...
					</p>
				</div>
				<!-- 注脚 -->
				<p>
					<!-- 附加信息 -->
					<span style="color: blue;">
						{{ document.created_at|date:'Y-m-d' }} 发布&nbsp;&nbsp;&nbsp;
					</span>
					<span style="color: darkred;">
						{{ document.updated_at|date:'Y-m-d' }} 更新
					</span>
				</p>
				<hr>
			</div>
			{% endfor %}
		</ul>
	{% else %}
		<p>没有找到匹配的文档。</p>
	{% endif %}
	
</div>

{% endblock content %}

templates/document/document_update.html
{% extends "base.html" %} {% load static %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文档标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ document.title }}">
                </div>
                <div class="form-group">
                    <label for="doc_type">文档类型</label>
                    <select type="text" class="form-control" id="doc_type" name="doc_type">
                        <option value="{{document.doc_type}}">{{document.doc_type}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="body">文档正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ document.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}