HPC_center/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #url for APP document
    path('document/', include('document.urls', namespace='document')),
    
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),

    path('tutorial/', include('tutorial.urls', namespace='tutorial')),

    path('', include('mainpage.urls')),

    path('ticket/', include('ticket.urls', namespace='ticket')),

    path('comment/', include('comment.urls', namespace='comment')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
# 引入path
from django.urls import path
from comment import views

# 正在部署的应用的名称
app_name = 'comment'

urlpatterns = [
    path('comment_post/<int:ticket_id>/', views.comment_post, name='comment_post')
]

ticket/urls.py
# 引入path
from django.urls import path
from ticket import views

# 正在部署的应用的名称
app_name = 'ticket'

urlpatterns = [
    path('ticket_list/', views.ticket_list, name='ticket_list'),
    path('ticket_userList/<int:id>', views.ticket_userList,name='ticket_userList'),
    path('ticket_detail/<int:id>/', views.ticket_detail, name='ticket_detail'),
    path('ticket_create/' , views.ticket_create, name='ticket_create'),
    path('ticket_delete/<int:id>/', views.ticket_delete, name='ticket_delete'),
    path('ticket_update/<int:id>/', views.ticket_update, name='ticket_update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
    path('display/<int:id>/', views.profile_display, name='display'),
]

ticket/models.py
# Create your models here.
from django.db import models
# 导入内建的User模型。
from django.contrib.auth.models import User
from django.urls import reverse
# timezone 用于处理时间相关事务。
from django.utils import timezone

# 博客帖子数据模型
class TicketPost(models.Model):
    # 帖子id,主键
    id = models.AutoField(primary_key=True)    
    # 帖子作者。参数 on_delete 用于指定数据删除的方式，避免两个关联表的数据不一致。
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 帖子标题。models.CharField 为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)
    # 帖子正文。保存大量文本使用 TextField
    body = models.TextField()
    # 帖子创建时间。参数 default=timezone.now 指定其在创建数据时将默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)
    # 帖子更新时间。参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)
    # 统计帖子浏览量
    total_views = models.PositiveIntegerField(default=0)
    # 帖子分类字段 未启用
    #ticket_type = models.CharField(max_length=50)

    # 内部类 class Meta 用于给 model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)

    # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
    def __str__(self):
        # return self.title 将帖子标题返回
        return self.title
    
    # 获取帖子地址
    def get_absolute_url(self):
        return reverse('ticket:ticket_detail', args=[self.id])

ticket/forms.py
from django import forms
from .models import TicketPost

class TicketPostForm(forms.ModelForm):
    class Meta:
        #指明数据模型来源
        model = TicketPost
        # 定义表单包含的字段
        fields = ('title', 'body')

ticket/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse

# 视图函数
from .models import TicketPost
from comment.models import Comment
def ticket_list(request):
    ticket = TicketPost.objects.all()
    # 需要传递给模板（templates）的对象
    context = { 'tickets': ticket }
    # render函数：载入模板，并返回context对象
    return render(request, 'tickets/list.html', context)

# 根据用户id返回该作者的帖子
def ticket_userList(request, id):
    ticket = TicketPost.objects.filter(author_id=id)
    context = {'tickets': ticket}
    return render(request, 'tickets/list.html', context)


import markdown
def ticket_detail(request, id):
    # 取出相应的文章
    tickets = TicketPost.objects.get(id=id)
    comments = Comment.objects.filter(ticket=id)
    # 统计帖子浏览量
    tickets.total_views += 1
    tickets.save(update_fields=['total_views'])
    #Markdown
    tickets.body = markdown.markdown(tickets.body, 
        extensions=[
        #包含 缩写、表格等常用扩展 
        'markdown.extensions.extra',
        # 语法高亮扩展
        'markdown.extensions.codehilite',
        ])
    # 需要传递给模板的对象
    context = { 'tickets': tickets, 'comments': comments}
    # 载入模板，并返回context对象
    return render(request, 'tickets/detail.html', context)
  

# 引入redirect用于重定向地址
from django.shortcuts import render, redirect
# 引入刚才定义的TicketPostForm表单类
from .forms import TicketPostForm

# 写文章的视图
def ticket_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        tickets_post_form = TicketPostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if tickets_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_ticket = tickets_post_form.save(commit=False)
            # 作者为当前请求的用户名
            new_ticket.author = request.user
            # 将新文章保存到数据库中
            new_ticket.save()
            # 完成后返回到文章列表
            return redirect("ticket:ticket_list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        tickets_post_form = TicketPostForm()
        # 赋值上下文
        context = { 'tickets_post_form': tickets_post_form }
        # 返回模板
        return render(request, 'tickets/create.html', context)
    
# 删文章
def ticket_delete(request, id):
    print(request.method)
    if request.method == 'POST':
        # 根据 id 获取需要删除的文章
        ticket = TicketPost.objects.get(id=id)
        # 调用.delete()方法删除文章
        ticket.delete()
        return redirect("ticket:ticket_list")
    else:
        return HttpResponse("仅允许post请求")
    
# 更新文章
def ticket_update(request, id):
    """
    更新文章的视图函数
    通过POST方法提交表单，更新titile、body字段
    GET方法进入初始表单页面
    id： 文章的 id
    """

    # 获取需要修改的具体文章对象
    ticket = TicketPost.objects.get(id=id)
    print(request.method == "POST")
    # 判断用户是否为 POST 提交表单数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        ticket_post_form = TicketPostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if ticket_post_form.is_valid():
            # 保存新写入的 title、body 数据并保存
            ticket.title = request.POST['title']
            ticket.body = request.POST['body']
            ticket.save()
            # 完成后返回到修改后的文章中。需传入文章的 id 值
            return redirect("ticket:ticket_detail", id=id)
            #return redirect("ticket:ticket_detail", id=id)
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    # 如果用户 GET 请求获取数据
    else:
        # 创建表单类实例
        ticket_post_form = TicketPostForm()
        # 赋值上下文，将 ticket 帖子对象也传递进去，以便提取旧的内容
        context = { 'ticket': ticket, 'ticket_post_form': ticket_post_form }
        # 将响应返回到模板中
        return render(request, 'tickets/update.html', context)

templates/tickets/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
  <div class="row">
    <div class="col-12">
      <br>
      <!-- 提交文章的表单 -->
      <form method="post" action=".">
        <!-- Django中需要POST数据的地方都必须有csrf_token -->
        {% csrf_token %}
        <!-- 文章标题 -->
        <div class="form-group">
          <!-- 标签 -->
          <label for="title">文章标题</label>
          <!-- 文本框 -->
          <input type="text" class="form-control" id="title" name="title">
        </div>
        <br>
        <br
        <!-- 文章正文 -->
        <div class="form-group">
          <label for="body">文章正文</label>
          <!-- 文本区域 -->
          <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
        </div>
        <!-- 提交按钮 -->
        <br>
        <button type="submit" class="btn btn-primary">完成</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/tickets/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <!--    <div class="row">-->
    <!-- 标题及作者 -->
    <h1 class="col-12 mt-4 mb-4">{{ tickets.title }}</h1>
    <div class="col-12 alert alert-primary">
        <div class="col-12">
            <a>作者：</a> <a href="{% url 'ticket:ticket_userList' tickets.author_id %}">{{ tickets.author }}</a>
            &nbsp
            <a>{{ tickets.created|date:'Y-m-d H:i:s' }}</a>
            &nbsp
            <!-- 只有作者可以修改文章 -->
            {% if user == tickets.author %}
            <a href="#" data-bs-toggle="modal" data-bs-target="#myModal">删除文章</a>
            <!-- 新增一个隐藏的表单 -->
            <form
            style="display:none;"
            id="safe_delete"
            action="{% url 'ticket:ticket_delete' tickets.id %}"
            method="POST"
            >
                {% csrf_token %}
                <button type="submit">发送</button>
            </form>
            &nbsp
            <a href="{% url 'ticket:ticket_update' tickets.id %}">编辑文章</a>
            {% endif %}
        </div>
    </div>
    <!-- 文章正文 -->
    <div class="col-12">
        <p>{{ tickets.body | safe}}</p>
    </div>

        <!-- 发表评论 -->
        <hr>
        {% if user.is_authenticated %}
            <div>
                <form 
                    action="{% url 'comment:comment_post' tickets.id %}" 
                    method="POST"
                >
                {% csrf_token %}
                    <div class="form-group">
                        <label for="body">
                            <strong>
                                我也要发言：
                            </strong>
                        </label>
                        <textarea 
                            type="text" 
                            class="form-control" 
                            id="body" 
                            name="body" 
                            rows="2"></textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary ">发送</button>                    
                </form>
            </div>
            <br>
        {% else %}
            <br>
            <h5 class="row justify-content-center">
                <!-- 接入登陆功能后添加 -->
                <!--请<a href="{% url 'userprofile:login' %}">登录</a>后回复 -->
                请<a href="#">登录</a>后回复
            </h5>
            <br>
        {% endif %}
    
    
    
        <!-- 显示评论 -->
        <h4>共有{{ comments.count }}条评论</h4>
        <div>
            {% for comment in comments %}
                <hr>
                <p>
                    <strong style="color: pink">
                        {{ comment.user }}
                    </strong> 于 
                    <span style="color: green">
                        {{ comment.created|date:"Y-m-d H:i:s" }}
                    </span> 时说：
                </p>
                <pre style="font-family: inherit; font-size: 1em;">
    {{ comment.body }}</pre>
            {% endfor %}
        </div>
    </div>
    

</div>


<!-- 模态框 -->
<div class="modal fade" id="myModal">
    <div class="modal-dialog modal-dialog-centered modal-sm">
        <div class="modal-content">
            <!-- 模态框头部 -->
            <div class="modal-header">
                <h4 class="modal-title">确认删除</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <!-- 模态框主体 -->
            <div class="modal-body">
                确认删除文章？
            </div>
            <!-- 模态框底部 -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="confirm_delete()">
                    确定
                </button>
            </div>
        </div>
    </div>
</div>
<script>
    // 删除文章的函数
    function confirm_delete() {
        document.getElementById("safe_delete").submit();
    }
</script>

{% endblock content %}

templates/tickets/list.html
<!doctype html>
</html>
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<br>
<div class="container">
    <div class="row ">
		<div class="col-sm-2">
			{% if user.is_authenticated %} 
				<a href="{% url 'ticket:ticket_create' %}" class="btn btn-primary">发帖</a>
			{% endif %}
		</div>
		{% comment %}<div class="col-sm-8 row">
			<form action="{% url 'ticket:ticket_search' %}" method="get" class="col-sm-8 row">
				<label for="search-input" class="col-sm-4">搜索文档：</label>
				<div class="col-sm-6	">
					<input type="text" class="form-control" id="search-input" name="q" value="{{ query }}">
				</div>
				<div class="form-group, col-sm-2"> 
					<button type="submit" class="btn btn-primary">搜索</button>
				</div>
			</form>
		</div> {% endcomment %}
	</div>
</div>
<br>
<br>
<!-- 定义放置文章标题的div容器 -->
<div class="container">
    {% for ticket in tickets %}
    <div class="row mt-2">
        <!-- 文章内容 -->
        <div class="col-sm-12">
            <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <!-- 摘要 -->
                <div class="card-body">
                    <h4 class="card-title">{{ ticket.title }}</h4>
                    <p class="card-text">{{ ticket.body|slice:'100' }}...</p>
                    <a href="{%url 'ticket:ticket_detail' ticket.id %}"  class="card-link">阅读本文</a>
                    <small class="col align-self-end" style="color: gray;">
                        浏览: {{ ticket.total_views }}
                    </small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/tickets/update.html
{% extends "base.html" %} {% load static %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="{% url 'ticket:ticket_update' ticket.id %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 ticket 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ ticket.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ ticket.body }}</textarea>
                </div>
                <br>
                <br>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}